name: BuildAndTest

on:
  workflow_dispatch:

jobs:
 build:
    name: Build and Test default scheme using iPhone simulator
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with: 
          xcode-version: '14.2'
      - name: Build And Test
        uses: sersoft-gmbh/xcodebuild-action@v2
        with:
          project: SampleJokes.xcodeproj
          scheme: SampleJokes
          destination: 'platform=iOS Simulator,name=iPhone 14,OS=17.0'
          action: test
      - name: Check Secret Variables
        run: ./work-on-secrets.sh $PROJECT_SCHEME_NAME
        env:
          PROJECT_SCHEME_NAME: ${{ secrets.PROJECT_SCHEME_NAME }}
    
