name: DisptachInputCheck

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: 'AWS SDK Check'
        default: 'QA'
        options: 
        - DEV
        - QA
        - PROD
      message:
        type: string
        required: true
      use-emoji:
        type: boolean
        default: true
        description: Upload to TestFlight
      environment:
        description: 'Environment to build'
        type: environment

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "${{ github.event.inputs.message }} ${{ fromJSON('["", "🥳"]')[github.event.inputs.use-emoji == 'true'] }} ${{ github.event.inputs.name }}"
    - name: Check Secrets
      run: echo "$TESTFLIGHT_KEY"
      env:
          TESTFLIGHT_KEY: ${{ vars.TESTFLIGHT_KEY }}
