name: BuildAndTest

on:
  pull_request:
    branches: 
      - main

jobs:
 SwiftLint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: GitHub Action for SwiftLint
      uses: norio-nomura/action-swiftlint@3.2.1

 build:
    name: Build and Test default scheme using iPhone simulator
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with: 
          xcode-version: '14.2'
      - name: Build And Test
        uses: sersoft-gmbh/xcodebuild-action@v2
        with:
          project: SampleJokes.xcodeproj
          scheme: SampleJokes
          destination: 'platform=iOS Simulator'
          action: test
